// Command rscgen generates a RouterOS provisioning script for deploying the
// awg-converter container and the WireGuard client that feeds it. It reads the
// real awg0.conf (including secrets) and therefore writes its output to a local
// file that must not be committed.
//
// The generated script never resets the router: it is applied on top of a
// working configuration whose prerequisites the user has prepared manually
// (container package, device-mode, uploaded files). See README.md.
package main

import (
	"flag"
	"log"
	"net"
	"os"
	"text/template"

	"github.com/nskforward/mikwg/internal/config"
)

type data struct {
	PrivateKey     string
	PeerPublic     string
	ServerIP       string
	ServerPort     string
	ClientAddr     string
	ClientAddrHost string
	MTU            int
	DNS            string
	WANList        string
	WANGW          string
	ContainerTar   string
	Container      string
	Image          string
	RegistryURL    string
	RootDir        string
	TmpDir         string
	VethIP         string
	VethIPHost     string
	GWIP           string
	WGName         string
	WGPort         int
	Keepalive      string
	RTTable        string
	AddrList       string
	ConnMark       string
	ContainerDNS   string
}

const script = `# RouterOS 7.24+ provisioning for mikwg (AmneziaWG 3.1 via WireGuard + container)
# Generated by rscgen. Secrets are included — keep this file private.
#
# mikwg NEVER resets the router. Prepare it yourself first (see README.md,
# "Подготовка роутера"), then run this script:
#   1) /system/backup/save name=pre-mikwg ; /export file=pre-mikwg-export
#      and DOWNLOAD both files to your workstation;
#   2) upload container-<ver>-arm64.npk to Files, reboot;
#   3) /system/device-mode/update container=yes, reboot;
#   4) put awg0.conf at /usb1/awg-config/awg0.conf;
#      {{if .Image}}the router pulls the image from {{.RegistryURL}} automatically
#      (internet access is required);{{else}}upload {{.ContainerTar}} to Files;{{end}}
#   5) make sure management access survives the changes (LAN port / Winbox-by-MAC);
#      see docs/safe-operations.md.
#
# Run with:  /import file=routeros.generated.rsc
# The script is idempotent: existing objects are detected and reused, so it is
# safe to import over a working configuration.
#
# Selective routing reuses the pre-existing list {{.AddrList}} and table
# {{.RTTable}}: destinations added to the list are routed through the tunnel.
# The default route is NOT modified. To route everything through the tunnel,
# add 0.0.0.0/0 to {{.AddrList}}.

# --- 1. Container network -------------------------------------------------
:if ([:len [/interface/veth find name="veth-awg"]] = 0) do={
    /interface/veth/add name=veth-awg address={{.VethIP}} gateway={{.GWIP}}
}
:if ([:len [/interface/bridge find name="br-awg"]] = 0) do={
    /interface/bridge/add name=br-awg
}
:if ([:len [/interface/bridge/port find interface="veth-awg"]] = 0) do={
    /interface/bridge/port/add bridge=br-awg interface=veth-awg
}
:if ([:len [/ip/address find address="{{.GWIP}}/30"]] = 0) do={
    /ip/address/add address={{.GWIP}}/30 interface=br-awg
}
# Allow the converter's replies back to the router's own WireGuard socket
# (the kernel listens on {{.WGPort}}, not 51820).
:if ([:len [/ip/firewall/filter find comment="mikwg converter in"]] = 0) do={
    /ip/firewall/filter/add chain=input action=accept protocol=udp dst-port={{.WGPort}} \
        in-interface=br-awg comment="mikwg converter in"
}
:if ([:len [/ip/firewall/nat find comment="mikwg converter snat"]] = 0) do={
    /ip/firewall/nat/add chain=srcnat action=masquerade src-address=10.99.0.0/30 \
        out-interface-list={{.WANList}} comment="mikwg converter snat"
}

# --- 2. Container ---------------------------------------------------------
:if ([:len [/container/mounts find where list="awg-cfg"]] = 0) do={
    /container/mounts/add list=awg-cfg src=/usb1/awg-config dst=/etc/awg mode=ro
}
# RouterOS refuses to start a container when /ip/dns has no static servers
# (e.g. DoH-only setup), so an explicit dns= override is required.
{{if .Image}}:if ([:len [/container/find name="{{.Container}}"]] = 0) do={
    # Pull the linux/arm64 image straight from {{.RegistryURL}}. tmpdir is a
    # global /container/config setting; point it at external storage, because
    # remote-image staging needs more space than the flash may have.
    /container/config/set registry-url={{.RegistryURL}} tmpdir={{.TmpDir}}
    /container/add remote-image={{.Image}} interface=veth-awg root-dir={{.RootDir}} \
        mountlists=awg-cfg entrypoint=/awg-converter dns={{.ContainerDNS}} \
        start-on-boot=yes logging=yes name={{.Container}}
}
{{else}}:if ([:len [/container/find name="{{.Container}}"]] = 0) do={
    /container/add file={{.ContainerTar}} interface=veth-awg mountlists=awg-cfg \
        entrypoint=/awg-converter dns={{.ContainerDNS}} start-on-boot=yes logging=yes \
        name={{.Container}}
}
{{end}}:if ([:len [/container/find name="{{.Container}}"]] > 0) do={
    :do { /container/start {{.Container}} } on-error={}
}

# --- 3. WireGuard (private key stays on the router) -----------------------
:if ([:len [/interface/wireguard find name="{{.WGName}}"]] = 0) do={
    /interface/wireguard/add name={{.WGName}} listen-port={{.WGPort}} mtu={{.MTU}} \
        private-key="{{.PrivateKey}}"
}
:if ([:len [/ip/address find address="{{.ClientAddr}}"]] = 0) do={
    /ip/address/add address={{.ClientAddr}} interface={{.WGName}}
}
:if ([:len [/interface/wireguard/peers find interface="{{.WGName}}"]] = 0) do={
    /interface/wireguard/peers/add interface={{.WGName}} public-key="{{.PeerPublic}}" \
        endpoint-address={{.VethIPHost}} endpoint-port=51820 persistent-keepalive={{.Keepalive}} \
        allowed-address=0.0.0.0/0
}

# --- 4. Anti-loop: reach the server via WAN, never via the tunnel ---------
# The route MUST point at the real WAN next-hop. An interface route (e.g.
# gateway=ether1) makes RouterOS ARP for the public server IP directly on the
# WAN L2 segment, which fails on ordinary ethernet uplinks and silently breaks
# the whole tunnel. When WANGW is empty it is auto-detected from the main
# default route (works for DHCP and for PPPoE, where the gateway is a link).
:do {
    :local wanGW "{{.WANGW}}"
    :if ([:len $wanGW] = 0) do={
        :local dr [/ip/route/find where dst-address="0.0.0.0/0" && routing-table=main && active=yes]
        :if ([:len $dr] > 0) do={ :set wanGW [/ip/route/get $dr gateway] }
    }
    :if ([:len $wanGW] > 0) do={
        :local ar [/ip/route/find where dst-address="{{.ServerIP}}/32" && comment="mikwg server via WAN"]
        :if ([:len $ar] = 0) do={
            /ip/route/add dst-address={{.ServerIP}}/32 gateway=$wanGW distance=1 \
                comment="mikwg server via WAN"
        } else={
            /ip/route/set $ar gateway=$wanGW
        }
    } else={
        :log warning "mikwg: no active default route; anti-loop route not added"
    }
}

# --- 5. Selective routing (reuses {{.AddrList}} / {{.RTTable}}) ------------
:if ([:len [/routing/table find name="{{.RTTable}}"]] = 0) do={
    /routing/table/add name={{.RTTable}} fib
}
:if ([:len [/ip/route find routing-table={{.RTTable}} dst-address="0.0.0.0/0" comment="mikwg vpn"]] = 0) do={
    /ip/route/add dst-address=0.0.0.0/0 gateway={{.WGName}} routing-table={{.RTTable}} \
        comment="mikwg vpn"
}
# Source NAT into the tunnel. A single-device Amnezia profile's server-side peer
# accepts only the client's own tunnel address ({{.ClientAddrHost}}) as the inner
# source. Without this, the router's traffic and LAN clients' traffic leave with
# their real addresses and the server silently drops them (WireGuard cryptokey
# routing), so only the handshake works and no data flows back.
:if ([:len [/ip/firewall/nat find comment="mikwg tunnel snat"]] = 0) do={
    /ip/firewall/nat/add chain=srcnat action=masquerade out-interface={{.WGName}} \
        comment="mikwg tunnel snat"
}
# --- Firewall: selective-routing mangle, rebuilt in a fixed order ---------
# Every rule whose comment starts with "mikwg:" is ours. Drop and re-add them on
# every import so the evaluation order is deterministic (the final state is
# idempotent); this is also how an older layout gets migrated. Order matters for
# the hot download direction: traffic arriving FROM the tunnel must leave mangle
# in the very first rule, and the address-list lookup must only ever run for NEW
# connections; established packets are steered by their connection-mark alone.
:foreach r in=[/ip/firewall/mangle/find where comment~"^mikwg:"] do={
    /ip/firewall/mangle/remove $r
}
# 1. Return traffic coming back FROM the tunnel must reach the LAN via the main
#    table. A reply still carries {{.ConnMark}}, so without this exception the
#    mark-routing rule below would route it straight back into the tunnel (reply
#    loop): the TCP handshake completes and replies show up in conntrack, but no
#    data ever reaches the client.
/ip/firewall/mangle/add chain=prerouting in-interface={{.WGName}} action=accept \
    passthrough=no comment="mikwg: vpn return"
# 2. Never mark traffic toward the server itself (loop protection).
/ip/firewall/mangle/add chain=prerouting dst-address={{.ServerIP}}/32 action=accept \
    passthrough=no comment="mikwg: anti-loop"
# 3. Inspect the destination list and mark the connection only when it is NEW.
/ip/firewall/mangle/add chain=prerouting connection-state=new dst-address-list={{.AddrList}} \
    action=mark-connection new-connection-mark={{.ConnMark}} passthrough=yes \
    comment="mikwg: mark connection"
# 4. Steer every packet of a marked connection by its mark alone (cheap).
/ip/firewall/mangle/add chain=prerouting connection-mark={{.ConnMark}} action=mark-routing \
    new-routing-mark={{.RTTable}} passthrough=no comment="mikwg: route to vpn"
# Router-originated traffic (e.g. its own DNS queries): the same connection-mark
# trick in the output chain, plus its own anti-loop guard.
/ip/firewall/mangle/add chain=output dst-address={{.ServerIP}}/32 action=accept \
    passthrough=no comment="mikwg: anti-loop out"
/ip/firewall/mangle/add chain=output connection-state=new dst-address-list={{.AddrList}} \
    action=mark-connection new-connection-mark={{.ConnMark}} passthrough=yes \
    comment="mikwg: mark connection out"
/ip/firewall/mangle/add chain=output connection-mark={{.ConnMark}} action=mark-routing \
    new-routing-mark={{.RTTable}} passthrough=no comment="mikwg: router via vpn"
# Clamp TCP MSS for tunnel-bound flows so LAN clients never emit segments larger
# than the tunnel MTU (avoids an MTU black hole for forwarded TCP).
/ip/firewall/mangle/add chain=forward protocol=tcp tcp-flags=syn connection-mark={{.ConnMark}} \
    action=change-mss new-mss=1360 comment="mikwg: mss clamp"
# FastTrack bypasses mangle and would break policy routing. Ensure every
# fasttrack rule excludes our connection mark (idempotent: a rule that already
# carries connection-mark=!{{.ConnMark}} is left untouched).
:foreach f in=[/ip/firewall/filter/find action=fasttrack-connection] do={
    :local cm [/ip/firewall/filter/get $f connection-mark]
    :if ($cm = "") do={
        /ip/firewall/filter/set $f connection-mark="!{{.ConnMark}}"
    } else={
        :if ($cm != "!{{.ConnMark}}") do={
            :log warning "mikwg: fasttrack rule has connection-mark=$cm; exclude !{{.ConnMark}} manually"
        }
    }
}

# --- 6. DNS (optional) ----------------------------------------------------
# Uncomment to let mikwg manage the router resolvers. They reach the tunnel only
# if these servers are present in {{.AddrList}}.
# /ip/dns/set servers={{.DNS}} allow-remote-requests=yes

# --- 7. Watchdog: restart the container on a stale handshake --------------
:if ([:len [/system/script find name="awg-watchdog"]] = 0) do={
    /system/script/add name=awg-watchdog source={
        :local p [/interface/wireguard/peers/find interface="{{.WGName}}"]
        :if ([:len $p] > 0) do={
            :local hs [/interface/wireguard/peers/get $p last-handshake]
            :if ($hs > 5m) do={
                :log warning "mikwg: stale handshake, restarting container"
                /container/stop {{.Container}}
                :delay 2s
                /container/start {{.Container}}
            }
        }
    }
}
:if ([:len [/system/scheduler find name="awg-watchdog"]] = 0) do={
    /system/scheduler/add name=awg-watchdog interval=1m on-event="/system/script/run awg-watchdog"
}
`

func main() {
	confPath := flag.String("conf", "awg0.conf", "path to the real AmneziaWG config")
	out := flag.String("out", "routeros.generated.rsc", "output script path")
	serverIP := flag.String("server-ip", "", "override server IP (default: from conf Endpoint)")
	wanGW := flag.String("wan-gw", "", "WAN next-hop for the anti-loop route; empty = auto-detect from the main default route (pass the gateway IP, not the interface)")
	wanList := flag.String("wan-iface-list", "WAN", "interface list used for masquerade")
	tar := flag.String("tar", "awg-converter-arm64.tar", "container image tar filename on the router (used when -image is empty)")
	image := flag.String("image", "nskforward/mikwg:1.0.0", "container image to pull from the registry; empty = import the tar instead")
	registry := flag.String("registry", "https://registry-1.docker.io", "registry the router pulls the image from")
	rootDir := flag.String("root-dir", "usb1/images/awg-converter", "on-router directory where the pulled image is extracted (external storage recommended)")
	tmpDir := flag.String("tmpdir", "usb1/tmp", "global /container/config tmpdir used while pulling the image (external storage recommended)")
	container := flag.String("container", "awg-converter", "container name")
	keepalive := flag.String("keepalive", "12s", "persistent keepalive interval")
	wgName := flag.String("wg-name", "awg", "WireGuard interface name")
	wgPort := flag.Int("wg-port", 13231, "WireGuard listen port on the router (local only)")
	rtTable := flag.String("rt-table", "to_vpn_table", "routing table for selective VPN routing (reused if it already exists)")
	addrList := flag.String("addr-list", "to_vpn_list", "firewall address list whose destinations are routed through the tunnel (reused if it already exists)")
	connMark := flag.String("conn-mark", "to_vpn_mark", "connection mark used for policy routing (fasttrack rules are made to exclude it)")
	containerDNS := flag.String("container-dns", "1.1.1.1", "DNS server the container inherits (required by RouterOS if /ip/dns has no static servers)")
	flag.Parse()

	cfg, err := config.ParseFile(*confPath)
	if err != nil {
		log.Fatalf("failed to parse %s: %v", *confPath, err)
	}
	if cfg.PrivateKey == "" || cfg.PeerPublicKey == "" {
		log.Fatal("conf is missing PrivateKey or peer PublicKey")
	}

	host, port := splitEndpoint(cfg.Endpoint)
	if *serverIP != "" {
		host = *serverIP
	}
	if host == "" {
		log.Fatal("server IP is unknown: set Endpoint in conf or pass -server-ip")
	}
	if port == "" {
		port = "51822"
	}

	d := data{
		PrivateKey:     cfg.PrivateKey,
		PeerPublic:     cfg.PeerPublicKey,
		ServerIP:       host,
		ServerPort:     port,
		ClientAddr:     cfg.Address,
		ClientAddrHost: hostOnly(cfg.Address),
		MTU:            cfg.MTU,
		DNS:            cfg.DNS,
		WANList:        *wanList,
		WANGW:          *wanGW,
		ContainerTar:   *tar,
		Container:      *container,
		Image:          *image,
		RegistryURL:    *registry,
		RootDir:        *rootDir,
		TmpDir:         *tmpDir,
		VethIP:         "10.99.0.2/30",
		VethIPHost:     "10.99.0.2",
		GWIP:           "10.99.0.1",
		WGName:         *wgName,
		WGPort:         *wgPort,
		Keepalive:      *keepalive,
		RTTable:        *rtTable,
		AddrList:       *addrList,
		ConnMark:       *connMark,
		ContainerDNS:   *containerDNS,
	}
	if d.MTU == 0 {
		d.MTU = 1408
	}
	if d.DNS == "" {
		d.DNS = "1.1.1.1,8.8.8.8"
	}

	f, err := os.Create(*out)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	tmpl := template.Must(template.New("rsc").Parse(script))
	if err := tmpl.Execute(f, d); err != nil {
		log.Fatalf("render: %v", err)
	}
	log.Printf("wrote %s (server %s:%s, wg iface %s, mtu %d, list %s, table %s, mark %s)",
		*out, host, port, d.WGName, d.MTU, d.AddrList, d.RTTable, d.ConnMark)
}

// hostOnly strips a CIDR suffix, e.g. "10.8.2.5/32" -> "10.8.2.5".
func hostOnly(s string) string {
	if h, _, err := net.ParseCIDR(s); err == nil {
		return h.String()
	}
	return s
}

func splitEndpoint(ep string) (host, port string) {
	if ep == "" {
		return "", ""
	}
	h, p, err := net.SplitHostPort(ep)
	if err != nil {
		return ep, ""
	}
	return h, p
}
